apiVersion: v1
kind: LimitRange
metadata:
  name: team-technology-limits
  namespace: team-technology
  labels:
    team: team-technology
    environment: production
spec:
  limits:
    - type: Container
      default:
        cpu: 4
        memory: 4Gi
      defaultRequest:
        cpu: 500m
        memory: 512Mi
